package org.coffeeshop.users.dtos;

// import com.fasterxml.jackson.annotation.JsonProperty;
// import jakarta.validation.constraints.NotBlank;
// import jakarta.validation.constraints.Size;

// public class StaffDto {

//     // read-only in practice (generated by DB)
//     private Long id;

//     @NotBlank
//     @Size(min = 3, max = 50)
//     private String username;

//     @NotBlank
//     @Size(min = 1, max = 50)
//     private String firstName;

//     @NotBlank
//     @Size(min = 1, max = 50)
//     private String lastName;



//     // e.g. "BARISTA", "MANAGER", "ADMIN"
//     @NotBlank
//     private String role;

//     private boolean active = true;

//     // plain password only for create/update, never returned to clients
//     @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
//     @NotBlank
//     @Size(min = 8, max = 100)
//     private String password;

//     // === getters & setters ===

//     public Long getId() {
//         return id;
//     }

//     public void setId(Long id) {        // can be omitted if you don’t allow client to set id
//         this.id = id;
//     }

//     public String getUsername() {
//         return username;
//     }

//     public void setUsername(String username) {
//         this.username = username;
//     }

//     public String getFirstName() {
//         return firstName;
//     }

//     public void setFirstName(String firstName) {
//         this.firstName = firstName;
//     }

//     public String getLastName() {
//         return lastName;
//     }

//     public void setLastName(String lastName) {
//         this.lastName = lastName;
//     }



//     public String getRole() {
//         return role;
//     }

//     public void setRole(String role) {
//         this.role = role;
//     }

//     public boolean isActive() {
//         return active;
//     }

//     public void setActive(boolean active) {
//         this.active = active;
//     }

//     public String getPassword() {       // present but write-only in JSON
//         return password;
//     }

//     public void setPassword(String password) {
//         this.password = password;
//     }
// }
